name: Collapsion
version: ${project.version}
main: net.kunmc.lab.collapsion.Collapsion
api-version: 1.15
commands:
  col:
    description: collapsion command.
    usage: /col <start/speed/reset/stop/resume> <value>
